runtime: java17
instance_class: F1

env_variables:
  SPRING_CLOUD_GCP_SQL_DATABASE_NAME: postgres
  SPRING_CLOUD_GCP_SQL_INSTANCE_CONNECTION_NAME: arte-386819:us-central1:arte-pg-db
  SPRING_DATASOURCE_CONTINUE_ON_ERROR: "true"
  SPRING_SQL_INIT_MODE: always
  SPRING_DATASOURCE_URL: jdbc:postgresql:///postgres?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=arte-386819:us-central1:arte-pg-db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_CLOUD_GCP_SQL_ENABLED: "true"
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQL95Dialect
