steps:
  - id: 'Stage app using mvn appengine plugin on mvn cloud build image'
    name: 'gcr.io/cloud-builders/mvn'
    dir: 'server'
    args: ['package', 'appengine:stage']
  - id: 'Deploy to app engine using gcloud image'
    name: 'gcr.io/cloud-builders/gcloud'
    dir: 'server'
    args: ['app', 'deploy', 'target/appengine-staging/app.yaml']
timeout: "1600s"